stages:
  - mavenbuild
  - maventest

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend
    - cd datesandduties
    - mvn package -B
    
maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend
    - cd datesandduties
    - mvn test
  artifacts:
    paths:
      - Backend/datesandduties/target/*.jar