stages:
  - mavenbuild
  - maventest
 # - androidbuild
 # - androidtest
  - autoDeploy

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend
    - cd datesandduties
    - mvn package
  only:
    refs:
      - master
    changes:
      - Backend/**/*
    
maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend
    - cd datesandduties
    - mvn test
  artifacts:
    paths:
      - Backend/datesandduties/target/*.jar
  only:
    refs:
      - master
    changes:
      - Backend/**/*
   
android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./Frontend/datesandduties/gradlew
  tags:
    - android_tag
  script: 
    - cd Frontend
    - cd datesandduties
    - ./gradlew build
  artifacts:
    paths:
      - Android_test/app/build/outputs/
      
android-test:
  image: javiersantos/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./Frontend/datesandduties/gradlew
  tags:
    - android_tag
  script:
    - cd Frontend
    - cd datesandduties
    - ./gradlew test

autoDeploy:
  stage: autoDeploy
  tags:
    - springboot_tag
  script:
    - cd Backend
    - cd datesandduties
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only:
    refs:
      - master
    changes:
      - Backend/**/*