package com.klin.sbtest.datesandduties;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private AccountRepository accountRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewAccount (@RequestParam String name, @RequestParam String email) {
	  
	  
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Account n = new Account();
    //n.setUsername(username);
    n.setName(name);
    n.setEmail(email);
    /*n.setGender(gender);
    n.setPassword(password);
    n.setPhone(phone);
    n.setCountry(country);
    n.setAge(age);*/
    accountRepository.save(n);
    return "Entry Saved!";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Account> getAllAccounts() {
    // This returns a JSON or XML with the users
    return accountRepository.findAll();
  }
}